Lazy request and response decode in CallList
lundberg/respx pull request #92
Opened 2020-10-10 17:51 UTC by SlavaSkvortsov

So, I did it in the most optimized way - you'll decode request and response only once and after you can access them as many as you want w/o extra decoding, trough respx.calls or trough pattern.calls. The only problem - it stores decoded Call in mock._Call object - it could be a bit hard for code reading

Fixes https://github.com/lundberg/respx/issues/90

2020-10-10 18:47 UTC, lundberg reviewed
Really nicely implemented!

It got me thinking though....what if we make the `stats` part of the `CallList`, maybe even have CallList extend `MagicMock` if possible and not too hacky?

Then we wouldn't need to pass `call_args_list` around.

Hey, we could even move the `record` method to `CallList` ;-)

In the `finally` statement we then could
```py
call = self.calls.record(request, response)
if pattern:
    pattern.calls.record(request, response, call=call)
    # or
    pattern.calls.add(call)
```

For backwards compatibility we can change `stats` to a transport/pattern property, returning `self.calls.stats`, or `self.calls` if a MagicMock, and fire a deprecation warning.

Thoughts @SlavaSkvortsov ?

2020-10-11 17:05 UTC, SlavaSkvortsov commented
What about this? `MagicMock` does some magic with magic methods, so I used the base class to keep `.assert_called_once()` logic. For me now it looks better and straightforward.

P.S. If everything is fine, could you add one more `hacktoberfest-accepted` tag, please? :)

2020-10-11 19:40 UTC, lundberg requested changes
Legit!

2020-10-11 19:40 UTC, lundberg commented on respx/models.py
> +        return self.calls
Not covered

2020-10-11 20:20 UTC, SlavaSkvortsov commented on respx/models.py
> +        return self.calls
Oh, right, I'll cover it tomorrow.

2020-10-12 19:10 UTC, SlavaSkvortsov commented on respx/api.py
> +stats = _deprecate_object(
I faced a problem here. In the previous version, I had here `stats = mock.stats`. It calls `stats` property and throws a warning. So, for getting the warning you only need to import API :) I tried to find any solution to fix it and finally came up with this crazy solution with metaprogramming. I don't like it, but it works as expected.

We can merge it and delete `respx.stats` at the next release or we can just remove it now, w/o deprecation warning. 

Or, mb, you can come up with a cleaner solution

2020-10-13 06:45 UTC, lundberg requested changes
For some reason, we got an other coverage issue in the transport for py 3.9.

2020-10-14 13:11 UTC, lundberg commented
Let's round this one up, I'd like to see this PR merged before next release.

Rebase and remove the deprecation warning in the property, and we're good to go @SlavaSkvortsov.

Documented deprecation can be added together with other docs changes for the release.

2020-10-14 18:02 UTC, SlavaSkvortsov commented
It is ready to merge :)

2020-10-15 06:59 UTC, lundberg approved these changes

2020-10-15 07:00 UTC, merged